# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
name: eShopOnWeb-Docker-ACR Build and Push

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: rg-az400-eshoponweb-xomnhala
  LOCATION: eastus
  TEMPLATE-FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION-ID: 341a411d-cdb3-4bb8-9db6-4955c9bcb54b
  WEBAPP-NAME: az400-webapp-xomnhalacuatui
