# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
name: eShopOnWeb-Docker-ACR Build and Push

on: [push, workflow_dispatch]

resources:
  repositories:
    - repository: self
      trigger: none


variables:
  azureServiceConnection: 'AZURE_CREDENTIALS'
  subscriptionId: '341a411d-cdb3-4bb8-9db6-4955c9bcb54b'
  resourceGroup: 'rg-az400-container-xomnhala'
  location: 'eastus'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest
