# NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
name: eShopOnWeb-Docker-ACR Build and Push

#Triggers (uncomment line below to use it)
#on: [push, workflow_dispatch]
on:
  push:
    branches:
      - 'main'

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: rg-az400-eshoponweb-xomnhala
  LOCATION: eastus
  TEMPLATE-FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION-ID: 341a411d-cdb3-4bb8-9db6-4955c9bcb54b
  WEBAPP-NAME: az400-webapp-xomnhalacuatui

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            user/app:latest
            user/app:1.0.0
            ghcr.io/user/app:latest
            ghcr.io/user/app:1.0.0  
